name: Build JavaScript Action Action
description: A GitHub Action for setting up useful stuff in NodeJS workflows.
runs:
  using: node12
  main: ./bootstrap-shim.js
  post: ./build/post.js
inputs:
  node-version-path:
    description: The path to the `.node-version` file.
    required: true
    default: ./.node-version
